Vagrant.configure("2") do |config|
config.vm.define :servidor do |servidor|
servidor.vm.box = "bento/centos-7.9"
servidor.vm.box = "JVega/Vagrant_pkg_Server"
servidor.vm.box_version = "0.0.3"
servidor.vm.network :private_network, ip: "192.168.50.3"
servidor.vm.hostname = "servidor"
servidor.vm.network "forwarded_port", guest: 80, host: 8080 
end
end